version: "3"

services:
  web:
    image: yooooomi/deluge:latest
    container_name: delugevpn
    ports:
      - 8112:8112
    volumes:
      - /home/pi/Documents/torrents/config:/config
    cap_add:
      - ALL
    devices:
      - "/dev/net/tun"
    environment:
      - LOCAL_NETWORK=192.168.0.0/16,169.254.0.0/16
      - DELUGE_DAEMON_LOG_LEVEL=debug
      - DELUGE_WEB_LOG_LEVEL=debug
      - UMASK=000
      - PUID=1000
      - PGID=1000
      - VPN_ENABLED=yes
      - VPN_USER=<user>
      - VPN_PASS=<password>
      - VPN_PROVIDER=NORDVPN